### ISSUE TITLE
Is it possible to Completely Disable the Private message LOCK feature ?

### ISSUE THREAD

**Issue by Blackyvk** [FabioZumbi12/UltimateChat#165]
I'm having this issue that no matter what, if someone else locks into a message private chat, they cannot leave it, even if uchat says that "you unlocked your private chat"... the last time everyone got locked onto a private chat and the only solution was to restart the server...

Is there a way you can add an option to completely disable this feature?

I dont have any other chat handling plugins (except for essentialsx) that might be interfering with this, but I have tried many things and nothing fixes it.

**Comment by FabioZumbi12** [comment]
Fixed on the latest version from our github

**Comment by Blackyvk** [comment]
I downloaded UltimateChat-1.8.8-b213-Universal some days ago and today I got stuck somehow in private chat with a friend

I got online on my server, used /tell name talked to my friend some minutes then I disconnected from server and hours later after logging in I noticed I couldnt talk in any channel again,  I have tried everything and I still cannot get out of private chat, i can private chat to other players but cannot use any other public channel, not even chat reload fixes it, i think the best way to solve this is by let us enable/disable  this feature.

**Comment by Sylensky** [comment]
I want to reopen this ticket as it seems that the issue still persists. I also suggest atleast an option to disable that feature completly or a general fix nonetheless.
