### ISSUE TITLE
[BUG] Channel delay

### ISSUE THREAD

**Issue by TylerS1066** [FabioZumbi12/UltimateChat#342]
**Describe the bug**
For some reason, there is an odd delay in changing channels.

**To Reproduce**
1. Talk in one channel
2. Switch to another channel via commands
3. Send a chat message
4. Sometimes the message goes in the first channel, sometimes the second

**Expected behavior**
I expect channel changes to be instantaneous and reliable

**Server and plugins versions (please complete the following information):**
 - Server: Spigot/Paper 1.12.2 & 1.16.5 servers with 1.16.5 bungeecord
 - Plugin Version: UltimateChat-1.9.1-b290-Universal
 - Java Version: AdoptOpenJDK 11.0.10

**Comment by TylerS1066** [comment]
Any updates on this?  I'd love to be able to continue using UltimateChat but this bug is really annoying for players and staff,

**Comment by TylerS1066** [comment]
*One year later*

Any progress on this?  It's infuriating to deal with this bug and really disappointing that there is zero support for this plugin.

**Comment by FabioZumbi12** [comment]
No fix man :/

I have no idea what can be the cause of this delay!

**Comment by TylerS1066** [comment]
We're now into year 3 of asking for a fix.  It's extremely disappointing the developer hasn't given us any indication if he's even been able to replicate the issue, nor asked us for more info to help them replicate the issue.

**Comment by TylerS1066** [comment]
Any updates on this?  We're onto year 4 now...

**Comment by FabioZumbi12** [comment]
(Finally) should be fixed on latest dev build http://host.areaz12server.net.br:8081/job/UltimateChat/lastBuild/ together compatibility with DiscordSRV

**Comment by TylerS1066** [comment]
![image](https://github.com/user-attachments/assets/630d4e5a-af41-4786-af1e-9194e708e78d)
I don't know what to tell you but it still happens

**Comment by TylerS1066** [comment]
Happens on both a build from f7077c423c857b6f29c62de4f8f0dd64df7a2d8f and on [1.9.2](https://www.spigotmc.org/resources/ultimatechat-1-7-1-20.23767/download?version=553364)

**Comment by FabioZumbi12** [comment]
How is you reproducing the problem? Try to print the console commands to reproduce please!
What i doing to reproduce is like on print (in red the problem like you reported)
![image](https://github.com/user-attachments/assets/2878e87d-e24d-4301-be5d-1f92dd9c35df)

But on newers versions this is not happening
The same sequence as the previous print
![image](https://github.com/user-attachments/assets/f61bef07-cb3b-427b-bf14-245ab241f520)

The problem was when we use the `/g message` where the channel was temporary on memory.

**Comment by TylerS1066** [comment]
From the screenshotted failure above:
```
[15:05:58] [Server thread/INFO]: TylerS1066 issued server command: /ch ot
[15:06:00] [Server thread/INFO]: TylerS1066 issued server command: /ch ad
[15:06:01] [Server thread/INFO]: Bungee message to channel Off-Topic from: Survival
```

**Comment by FabioZumbi12** [comment]
I still cant reproduce with the same commands. Can you print your `/uchat ?` output?
![image](https://github.com/user-attachments/assets/0f79a104-a67f-4923-8ebd-193bb4d6be28)

**Comment by TylerS1066** [comment]
`- UChat full version: UltimateChat-1.9.2-b303-Universal.jar`

**Comment by FabioZumbi12** [comment]
Can you try the latest dev build? http://host.areaz12server.net.br:8081/job/UltimateChat/lastBuild/

(If you is using Uchat JDA, you cant test as the snashot JDA is bugged)

**Comment by TylerS1066** [comment]
I had another interesting failure which may or may not be related.  This time I was direct messaging somebody, stopped for ~10-15 minutes, then sent a chat message and it went to the direct message instead of the public chat channel.

I have not had any issues with channel changing being delayed yet, which is a good sign.
